###
GET http://localhost:5000/api/dashboard

###
POST http://localhost:5000/api/auth/google
Content-Type: application/json

{
    "code": "4/0Aci98E_40t_oBqSaJFSU_ISgC6Lb9p1V6aupTTWKZAZn5cuSzhn4UOIFWXySVthgo5yTZA",
    "codeVerifier": "UcA6msN9WwiWbYZAEJjAtwIY00vrdfJvUSx-pFn7AN4"
}

###
GET http://localhost:5000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNTRjYjM4YS05NTU1LTQ4NjAtYTk3OS1lYjNhZGE3NzAwNmIiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzc0MjUyNTA1LCJleHAiOjE3NzQyNjMzMDV9.dXsR5D-YQXVaqGvtR7-rKlcz0g931wX_vWSPFOm8S_c

###
GET http://localhost:5000/gmail/connect
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGE4NDE0ZC03OWZmLTQ4ZmEtOGNjMC03ZjZkZjRlNDU4NTYiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzcwOTc0MjY2LCJleHAiOjE3NzA5ODUwNjZ9.eGmJf5VOXCPqDCNmHxk3JuQj9Vk0eH5fNKUYEM5dsu0

###
GET http://localhost:5000/gmail/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNTRjYjM4YS05NTU1LTQ4NjAtYTk3OS1lYjNhZGE3NzAwNmIiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzc0MjUyNTA1LCJleHAiOjE3NzQyNjMzMDV9.dXsR5D-YQXVaqGvtR7-rKlcz0g931wX_vWSPFOm8S_c

### 
GET http://localhost:5000/gmail/scan/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMTkzYjM1My0wMTNjLTQwYWQtOGYyNy05ZmI3OWFkNzYwZjAiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzcwNzg5MjI1LCJleHAiOjE3NzA3OTI4MjV9.Nn1w6Ad_bAbR8KzfYEbBFaTOCwZ2OEBPz8vjIOTOjSA

###
POST http://localhost:5000/gmail/historical-scan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiZWQ1YjkwOS0wMTFiLTQxM2UtODIxMC01MjFhYzEzNzZhYzQiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzc0MjYxNjI2LCJleHAiOjE3NzQyNzI0MjZ9.ySC7GnAuWuF0J6gj-9rF9jxiWYTmfBqyPtCIQBf__lE

###
GET http://localhost:5000/api/subscriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNTRjYjM4YS05NTU1LTQ4NjAtYTk3OS1lYjNhZGE3NzAwNmIiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzc0MjUyNTA1LCJleHAiOjE3NzQyNjMzMDV9.dXsR5D-YQXVaqGvtR7-rKlcz0g931wX_vWSPFOm8S_c

###
GET http://localhost:5000/api/subscriptions/df0f3d92-fa8e-4249-be70-0c193e26e052
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGE4NDE0ZC03OWZmLTQ4ZmEtOGNjMC03ZjZkZjRlNDU4NTYiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzcxMjI3NzIwLCJleHAiOjE3NzEyMzg1MjB9.RG8o3U8Jpd_q2dyA9FowpsMW89fVakf80PGaw8tbqY8

###
POST http://localhost:5000/api/subscriptions/df0f3d92-fa8e-4249-be70-0c193e26e052/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGE4NDE0ZC03OWZmLTQ4ZmEtOGNjMC03ZjZkZjRlNDU4NTYiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzcxMjI3NzIwLCJleHAiOjE3NzEyMzg1MjB9.RG8o3U8Jpd_q2dyA9FowpsMW89fVakf80PGaw8tbqY8

###
DELETE http://localhost:5000/api/subscriptions/87303b15-755f-4fc7-88d9-85ea71d0e947
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGE4NDE0ZC03OWZmLTQ4ZmEtOGNjMC03ZjZkZjRlNDU4NTYiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzcxMjI3NzIwLCJleHAiOjE3NzEyMzg1MjB9.RG8o3U8Jpd_q2dyA9FowpsMW89fVakf80PGaw8tbqY8

###
PATCH  http://localhost:5000/api/subscriptions/f1019a70-f62d-407f-99eb-4d83d9570c42
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGE4NDE0ZC03OWZmLTQ4ZmEtOGNjMC03ZjZkZjRlNDU4NTYiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzcxMjI3NzIwLCJleHAiOjE3NzEyMzg1MjB9.RG8o3U8Jpd_q2dyA9FowpsMW89fVakf80PGaw8tbqY8
Content-Type: application/json

{
    "amount": 649
}


###
GET http://localhost:5000/api/subscriptions/upcoming-renewals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGE4NDE0ZC03OWZmLTQ4ZmEtOGNjMC03ZjZkZjRlNDU4NTYiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzcwOTc0MjY2LCJleHAiOjE3NzA5ODUwNjZ9.eGmJf5VOXCPqDCNmHxk3JuQj9Vk0eH5fNKUYEM5dsu0

# https://accounts.google.com/o/oauth2/v2/auth?client_id=635040404028-ta16mb8rt1q466k9re2c6hq60a6rrf75.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fcallback&response_type=code&scope=openid%20email%20profile


# https://accounts.google.com/o/oauth2/v2/auth?client_id=635040404028-ta16mb8rt1q466k9re2c6hq60a6rrf75.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fauth%2Fcallback&response_type=code&scope=openid%20email%20profile


# https://accounts.google.com/o/oauth2/v2/auth?client_id=635040404028-ta16mb8rt1q466k9re2c6hq60a6rrf75.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fauth%2Fcallback&response_type=code&scope=openid%20email%20profile&code_challenge=d9Fl49h7JqCGMc-Qz05Ecv5ig7C-15TLzbORvZ7UjXg&code_challenge_method=S256

# http://localhost:5000/gmail/connect?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiZWQ1YjkwOS0wMTFiLTQxM2UtODIxMC01MjFhYzEzNzZhYzQiLCJlbWFpbCI6ImRldmFuc2hrYXBhZGlhMDBAZ21haWwuY29tIiwiaWF0IjoxNzc0MjYxNjI2LCJleHAiOjE3NzQyNzI0MjZ9.ySC7GnAuWuF0J6gj-9rF9jxiWYTmfBqyPtCIQBf__lE